### ISSUE TITLE
Add signers to config that can be referenced by repositories

### ISSUE THREAD

**Issue by phisco** [sighupio/opa-notary-connector#25]
Current implementation is:
```yaml
repositories:
- name: "localhost.*"
  priority: 10
  trust:
    enabled: true
    trustServer: "https://notary-server.notary.svc.cluster.local:4443"
    signers:
    - role: "targets/jenkins"
      publicKey: "H" # base64 encoded public key
```

expected output:
```yaml
repositories:
- name: "localhost.*"
  priority: 10
  trust:
    enabled: true
    trustServer: "https://notary-server.notary.svc.cluster.local:4443"
    signers:
    - role: "targets/jenkins"
      signer: jenkins
- name: "test.*"
  priority: 10
  trust:
    enabled: true
    trustServer: "https://another-notary-server.notary.svc.cluster.local:4443"
    signers:
    - role: "targets/jenkins"
      signer: jenkins
    - role: "targets/tester"
      publicKey: "H" # base64 encoded public key
signers:
- name: jenkins
  publicKey: "H" # base64 encoded public key
```

should update the config validate function accordingly
